name: Wiederholung Techstarter
run-name: AWS create resources
on: [push]
jobs:
  Deploy-App:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      # Wir installieren die dependencies (terraform, aws)
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - name: Check if aws cli is installed
        run: |
          aws --version
      - uses: hashicorp/setup-terraform@v2
      - run: terraform version
      # Konfiguriere die AWS CLI
      - run: mkdir -p ~/.aws/
      - run: echo "$super_secret" > ~/.aws/credentials
        env: # Erstelle ein Github Secret AWS_CONFIG!
          super_secret: ${{ secrets.AWS_CONFIG }}
      - run: cat ~/.aws/credentials
      - run: aws configure list-profiles
      - run: aws s3 ls --region eu-central-1 --profile techstarter
      # Create terraform
      - run: terraform -chdir=terraform/ init -backend-config="bucket=${STATE_BUCKET}"
        env: 
          STATE_BUCKET: ${{ secrets.TF_BUCKET }}
      - run: terraform -chdir=terraform/ plan
      - run: terraform -chdir=terraform/ apply -auto-approve
      - run: terraform -chdir=terraform/ output -raw inventory > ansible/inventory.ini
      - run: terraform -chdir=terraform/ output -raw private_key > ssh_key
      # Setup SSH for ansible
      - name: Setup SSH 
        shell: bash
        run: |
          mkdir -p /home/runner/.ssh/
          cp ssh_key /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa
          ssh-keyscan -t rsa $(cat /home/runner/.ssh/id_rsa) >> /home/runner/.ssh/known_hosts
      # Run the ansible playbook
      - name: Run ansible
        run: |
          service ssh status
          cd ansible
          ansible-playbook -vvv --private-key /home/runner/.ssh/id_rsa -u ubunut -i inventory.ini playbooks/playbook.yml
